POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "A01636629@tec.mx",
  "password": "password",
  "firstName": "Jorge Luis",
  "lastName": "Salgado Ledezma",
  "phone": "3317095745",
  "age": 24,
  "nickName": "MasterUser"
}
###
POST http://localhost:8080/auth/1
Content-Type: application/json

{
  "email": "A01636629@tec.mx",
  "password": "password",
  "firstName": "Jorge Luis",
  "lastName": "Salgado Ledezma",
  "phone": "3317095745",
  "age": 24,
  "nickName": "MasterUser",
  "state": "Jalisco",
  "city": "Guadalajara",
  "street": "Av. Vallarta",
  "externalNumber": "503",
  "suburb": "Americana",
  "zipCode": "44110"
}

###
GET http://localhost:8080/auth/1

###
GET http://localhost:8080/auth