POST http://localhost:8080/products?category_id=1&user_id=1
Content-Type: application/json

{
    "name": "Audifonos Bose",
    "description": "Excelente calidad, solo se usaron una vez",
    "price": 1000,
    "category_id": 1,
    "user_id": 1
}

GET http://localhost:8080/product/2